title: Stimulus Tailwind Components Playground
email: github@chiefpansancolt.dev
description: >-
  Playground for Stimulus Tailwind Components, a node
  package that provides StimulusJS build controllers for
  Tailwind based Components, currently supports
  (Notifications, Theme, Switch, Modal).
domain: chiefpansancolt.dev
url: https://stimulus-tailwind-play.chiefpansancolt.dev
baseurl: /
twitter_username: chiefpansancolt
github_username: chiefpansancolt
theme: null
encoding: utf-8
markdown: CommonMarkGhPages
commonmark:
  extensions: ['strikethrough', 'autolink', 'table', 'tagfilter', 'tasklist']
highlighter: rouge
exclude:
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - tailwind.config.js
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: 'assets'
    values:
      sitemap: false
  - scope:
      path: 'playground/modal/snippets'
    values:
      sitemap: false
  - scope:
      path: 'playground/notification/snippets'
    values:
      sitemap: false
  - scope:
      path: 'playground/switch/snippets'
    values:
      sitemap: false
  - scope:
      path: 'playground/theme/snippets'
    values:
      sitemap: false

copyright: Copyright &copy; 2023 Christopher Pezza, All rights reserved.

links:
  home: /
  repo: https://github.com/chiefpansancolt/stimulus-tailwind-components
  roadmap: https://github.com/users/chiefpansancolt/projects/3
  discord: https://discord.com
  tailwindcss: https://tailwindcss.com/docs/installation
  stimulus: https://stimulus.hotwired.dev/handbook/installing
  tailwindui: https://tailwindui.com
  viewcomponents: https://viewcomponent.org
  examples: /
  installation: https://stimulus-tailwind.chiefpansancolt.dev/docs/installation
  change_log: https://stimulus-tailwind.chiefpansancolt.dev/docs/change_log
  docs:
    notification: https://stimulus-tailwind.chiefpansancolt.dev/docs/notification
    theme: https://stimulus-tailwind.chiefpansancolt.dev/docs/theme
    switch: https://stimulus-tailwind.chiefpansancolt.dev/docs/switch
    modal: https://stimulus-tailwind.chiefpansancolt.dev/docs/modal
  playground:
    notification: /playground/notification
    theme: /playground/theme
    switch: /playground/switch
    modal: /playground/modal
