title: Stimulus Tailwind Components Playground
email: github@chiefpansancolt.dev
description: >-
  Documentation for Stimulus Tailwind Components, a node
  package that provides StimulusJS build controllers for
  Tailwind based Components, currently supports (Notifications).
domain: chiefpansancolt.github.io
url: https://chiefpansancolt.github.io
baseurl: /stimulus-tailwind-playground/
twitter_username: chiefpansancolt
github_username: chiefpansancolt
markdown: CommonMarkGhPages
commonmark:
  extensions: ['strikethrough', 'autolink', 'table', 'tagfilter', 'tasklist']
highlighter: rouge

copyright: Copyright &copy; 2023 Christopher Pezza, All rights reserved.

links:
  home: /
  repo: https://github.com/chiefpansancolt/stimulus-tailwind-components
  roadmap: https://github.com/users/chiefpansancolt/projects/3
  discord: https://discord.com
  tailwindcss: https://tailwindcss.com/docs/installation
  stimulus: https://stimulus.hotwired.dev/handbook/installing
  tailwindui: https://tailwindui.com
  viewcomponents: https://viewcomponent.org
  examples: /
  installation: https://stimulus-tailwind.chiefpansancolt.dev/docs/installation
  change_log: https://stimulus-tailwind.chiefpansancolt.dev/docs/change_log
  docs:
    notification: https://stimulus-tailwind.chiefpansancolt.dev/docs/notification
    theme: https://stimulus-tailwind.chiefpansancolt.dev/docs/theme
    switch: https://stimulus-tailwind.chiefpansancolt.dev/docs/switch
    modal: https://stimulus-tailwind.chiefpansancolt.dev/docs/modal
  playground:
    notification: /playground/notification
    theme: /playground/theme
    switch: /playground/switch
    modal: /playground/modal
