blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/chiefpansancolt/stimulus-tailwind-components/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
  - name: Bug
    url: https://github.com/chiefpansancolt/stimulus-tailwind-components/issues/new?assignees=chiefpansancolt&labels=bug%2Ctriage&template=bug_report.yml&title=%5BBug%5D%3A+
    about: Found a bug? Submit it here on the Stimulus Tailwind Components project.
  - name: Feature Request
    url: https://github.com/chiefpansancolt/stimulus-tailwind-components/issues/new?assignees=chiefpansancolt&labels=enhancement%2Ctriage&template=feature_request.yml&title=%5BEnhancement%5D%3A+
    about: Have an idea? Submit it here on the Stimulus Tailwind Components project.
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
